services:
  alice:
    build:
      context: .
      dockerfile: eioud.dockerfile
    container_name: alice
    networks:
      - eiou-network-compose
    environment:
      - QUICKSTART=alice
    ports:
      - "8081:80"
    volumes:
      - alice-mysql-data:/var/lib/mysql
      - ./src:/etc/eiou/src
      - ./public:/app/public
    restart: unless-stopped

  bob:
    build:
      context: .
      dockerfile: eioud.dockerfile
    container_name: bob
    networks:
      - eiou-network-compose
    environment:
      - QUICKSTART=bob
    ports:
      - "8082:80"
    volumes:
      - bob-mysql-data:/var/lib/mysql
      - ./src:/etc/eiou/src
      - ./public:/app/public
    restart: unless-stopped

  carol:
    build:
      context: .
      dockerfile: eioud.dockerfile
    container_name: carol
    networks:
      - eiou-network-compose
    environment:
      - QUICKSTART=carol
    ports:
      - "8083:80"
    volumes:
      - carol-mysql-data:/var/lib/mysql
      - ./src:/etc/eiou/src
      - ./public:/app/public
    restart: unless-stopped

  daniel:
    build:
      context: .
      dockerfile: eioud.dockerfile
    container_name: daniel
    networks:
      - eiou-network-compose
    environment:
      - QUICKSTART=daniel
    ports:
      - "8084:80"
    volumes:
      - daniel-mysql-data:/var/lib/mysql
      - ./src:/etc/eiou/src
      - ./public:/app/public
    restart: unless-stopped

networks:
  eiou-network-compose:
    driver: bridge
    name: eiou-network-compose

volumes:
  alice-mysql-data:
    name: alice-mysql-data
  bob-mysql-data:
    name: bob-mysql-data
  carol-mysql-data:
    name: carol-mysql-data
  daniel-mysql-data:
    name: daniel-mysql-data