services:
  eioud:
    build:
      context: .
      dockerfile: eioud.dockerfile
    container_name: eioud-single
    networks:
      - eiou-network-compose
    environment:
      - QUICKSTART=eioud
    volumes:
      - eioud-mysql-data:/var/lib/mysql
      - eioud-files:/etc/eiou/
      - eioud-index:/var/www/html
      - eioud-eiou:/usr/local/bin/
    restart: unless-stopped

networks:
  eiou-network-compose:
    driver: bridge
    name: eiou-network-compose

volumes:
  eioud-mysql-data:
    name: eioud-mysql-data
  eioud-files:
    name: eioud-files
  eioud-index:
    name: eioud-index
  eioud-eiou:
    name: eioud-eiou