#!/bin/sh
# Copyright 2025 Adrien Hubert (adrien@eiou.org)

############################ Testing #############################
# TOR Key Permissions Test
# Verifies that TOR hidden service key files have correct permissions
# and ownership as required by the TOR daemon.
#
# TOR requires:
# - Directory: 700 (drwx------)
# - Files: 600 (-rw-------)
# - Owner: debian-tor
#
# This test validates the key files generated by TorKeyDerivation.php
# are properly secured and readable by TOR.
##################################################################

testname="torKeyPermissionsTest"
totaltests=0
passed=0
failure=0

HS_DIR="/var/lib/tor/hidden_service"

# Files to check
HS_FILES="hs_ed25519_secret_key hs_ed25519_public_key hostname"

for container in "${containers[@]}"; do
    totaltests=$(( totaltests + 1 ))
    containerPassed=true

    # Test 1: Verify hidden service directory exists
    dirExists=$(docker exec $container test -d "$HS_DIR" && echo "yes" || echo "no")
    if [ "$dirExists" != "yes" ]; then
        printf "\t   ${testname} for %s ${RED}FAILED${NC} - Hidden service directory does not exist\n" ${container}
        failure=$(( failure + 1 ))
        continue
    fi

    # Test 2: Verify directory permissions (should be 700)
    dirPerms=$(docker exec $container stat -c '%a' "$HS_DIR" 2>/dev/null)
    if [ "$dirPerms" != "700" ]; then
        printf "\t   ${testname} for %s ${YELLOW}WARNING${NC} - Directory permissions: ${dirPerms} (expected 700)\n" ${container}
        # Not a hard failure as TOR may still work
    fi

    # Test 3: Verify directory ownership
    dirOwner=$(docker exec $container stat -c '%U' "$HS_DIR" 2>/dev/null)
    if [ "$dirOwner" != "debian-tor" ]; then
        printf "\t   ${testname} for %s ${YELLOW}WARNING${NC} - Directory owner: ${dirOwner} (expected debian-tor)\n" ${container}
    fi

    # Test 4: Verify each key file exists and has correct permissions
    for keyFile in $HS_FILES; do
        filePath="${HS_DIR}/${keyFile}"

        # Check file exists
        fileExists=$(docker exec $container test -f "$filePath" && echo "yes" || echo "no")
        if [ "$fileExists" != "yes" ]; then
            printf "\t   ${testname} for %s ${RED}FAILED${NC} - Missing file: ${keyFile}\n" ${container}
            containerPassed=false
            continue
        fi

        # Check file permissions (should be 600)
        filePerms=$(docker exec $container stat -c '%a' "$filePath" 2>/dev/null)
        if [ "$filePerms" != "600" ]; then
            printf "\t   ${testname} for %s ${YELLOW}WARNING${NC} - ${keyFile} permissions: ${filePerms} (expected 600)\n" ${container}
        fi

        # Check file ownership
        fileOwner=$(docker exec $container stat -c '%U' "$filePath" 2>/dev/null)
        if [ "$fileOwner" != "debian-tor" ]; then
            printf "\t   ${testname} for %s ${YELLOW}WARNING${NC} - ${keyFile} owner: ${fileOwner} (expected debian-tor)\n" ${container}
        fi

        # Check file is non-empty
        fileSize=$(docker exec $container stat -c '%s' "$filePath" 2>/dev/null)
        if [ "$fileSize" = "0" ]; then
            printf "\t   ${testname} for %s ${RED}FAILED${NC} - ${keyFile} is empty\n" ${container}
            containerPassed=false
        fi
    done

    # Test 5: Verify TOR can read the keys (service is running)
    torStatus=$(docker exec $container service tor status 2>&1)
    if ! echo "$torStatus" | grep -q "running"; then
        printf "\t   ${testname} for %s ${RED}FAILED${NC} - TOR not running (possible permission issue)\n" ${container}
        # Check TOR logs for permission errors
        torErrors=$(docker exec $container grep -i "permission\|denied\|failed to load" /var/log/tor/log 2>/dev/null | tail -3)
        if [ -n "$torErrors" ]; then
            printf "\t   TOR log errors:\n"
            echo "$torErrors" | while read line; do
                printf "\t     ${line}\n"
            done
        fi
        containerPassed=false
    fi

    if [ "$containerPassed" = true ]; then
        printf "\t   ${testname} for %s ${GREEN}PASSED${NC}\n" ${container}
        passed=$(( passed + 1 ))
    else
        failure=$(( failure + 1 ))
    fi

done

succesrate "${totaltests}" "${passed}" "${failure}" "'tor key permissions'"

##################################################################
