<?php
# Copyright 2025-2026 Vowels Group, LLC

namespace Eiou\Services;

use InvalidArgumentException;

/**
 * PluginNginxConfigService
 *
 * Renders the nginx snippet that routes plugin-served HTTP traffic to
 * each sandboxed plugin's PHP-FPM pool. Lives at
 * /etc/nginx/snippets/eiou-plugins.conf, which is included from
 * eiou-locations.conf so both HTTP and HTTPS server blocks pick it up.
 *
 * URL contract: `/gui/plugin/<plugin-id>/...` routes to that plugin's
 * pool. The plugin id appears in the URL so operators (and tests) can
 * see which plugin a request hit without trawling FPM logs.
 *
 * The snippet is regenerated in full every time any sandboxed plugin
 * enables or disables. PHP renders the content, the supervisor writes
 * it (since /etc/nginx/snippets/ is root-only), and nginx -t verifies
 * it before reload — so a malformed entry from a buggy plugin cannot
 * take down the wallet's routes.
 *
 * See docs/PLUGINS.md (Sandboxing) for the broader trust model.
 */
class PluginNginxConfigService
{
    /** Bearer shape accepted by the public-route preflight. Wide
     *  enough for opaque tokens encoded as hex, base64url, or
     *  ULID-style. Plugins do the actual credential check; the host
     *  only refuses values that obviously can't be a token at all.
     */
    public const PUBLIC_BEARER_REGEX = '^Bearer [A-Za-z0-9._~+/=-]{8,256}$';

    private bool $publicRoutesEnabled;

    public function __construct(bool $publicRoutesEnabled = false)
    {
        $this->publicRoutesEnabled = $publicRoutesEnabled;
    }

    /**
     * Render the complete nginx snippet from a list of sandboxed
     * plugins. The list MUST be authoritative — anything not in the
     * list ends up with no route after the next reload.
     *
     * Each entry may carry an optional `public_routes` list. When the
     * service is constructed with $publicRoutesEnabled=true, every
     * such entry produces an additional `location = /p/<id>/<action>`
     * block alongside the IPC `/gui/plugin/<id>/` block. When the
     * flag is off, public_routes are silently dropped — operators
     * opt in via EIOU_PUBLIC_PLUGIN_ROUTES.
     *
     * @param list<array{
     *     plugin_id:string,
     *     system_user:string,
     *     public_routes?:list<array{method:string,action:string,max_body_bytes?:int,rate_per_minute?:int}>
     * }> $sandboxedPlugins
     */
    public function renderSnippet(array $sandboxedPlugins): string
    {
        $lines = [
            "# Copyright 2025-2026 Vowels Group, LLC",
            "# Auto-generated by Eiou\\Services\\PluginNginxConfigService.",
            "# Hand edits are overwritten on every plugin enable/disable.",
            "# See docs/PLUGINS.md (Sandboxing).",
            "",
        ];

        if ($sandboxedPlugins === []) {
            $lines[] = "# (no sandboxed plugins enabled)";
            $lines[] = "";
            return implode("\n", $lines);
        }

        foreach ($sandboxedPlugins as $entry) {
            $pluginId = (string) ($entry['plugin_id'] ?? '');
            $systemUser = (string) ($entry['system_user'] ?? '');
            $this->validatePluginId($pluginId);
            $this->validateSystemUser($systemUser);

            // Block shape: every /gui/plugin/<id>/* request lands at the
            // plugin's own FPM socket. The plugin's open_basedir + UID
            // are the real boundary; this just routes traffic to it.
            //
            // SCRIPT_FILENAME pins to the plugin's __dispatch entry
            // point so plugin code never picks the URL — it gets a
            // structured envelope from PHP-FPM with the path captured
            // in PATH_INFO. Plugin must provide /etc/eiou/plugins/<id>/
            // __dispatch.php; absence yields 404 without breaching the
            // pool's open_basedir.
            // fastcgi_split_path_info needs EXACTLY two captures by
            // nginx contract: the first becomes $fastcgi_script_name,
            // the second becomes $fastcgi_path_info. We pin
            // SCRIPT_FILENAME explicitly below so the prefix capture is
            // ornamental, but nginx still requires the second capture
            // to exist or fails `nginx -t` with "must have 2 captures".
            $lines[] = "location ^~ /gui/plugin/{$pluginId}/ {";
            $lines[] = "    fastcgi_pass unix:/run/php/eiou-plugin-{$systemUser}.sock;";
            $lines[] = "    fastcgi_split_path_info ^(/gui/plugin/{$pluginId})(/.*)$;";
            $lines[] = "    include fastcgi_params;";
            $lines[] = "    fastcgi_param SCRIPT_FILENAME /etc/eiou/plugins/{$pluginId}/__dispatch.php;";
            $lines[] = "    fastcgi_param SCRIPT_NAME     /gui/plugin/{$pluginId}/__dispatch.php;";
            $lines[] = "    fastcgi_param PATH_INFO       \$fastcgi_path_info;";
            $lines[] = "    fastcgi_read_timeout 30s;";
            $lines[] = "}";
            $lines[] = "";

            // Public-route blocks live alongside the IPC block. One
            // location per declared public route — keeps method
            // matching, body size, and (future) rate-limit zones
            // expressible per route without runtime branching in
            // nginx.
            $publicRoutes = $entry['public_routes'] ?? [];
            if ($this->publicRoutesEnabled && is_array($publicRoutes) && $publicRoutes !== []) {
                foreach ($publicRoutes as $route) {
                    $line = $this->renderPublicRouteBlock($pluginId, $systemUser, $route);
                    if ($line !== null) {
                        $lines[] = $line;
                        $lines[] = "";
                    }
                }
            }
        }

        return implode("\n", $lines);
    }

    /**
     * Render one `location = /p/<id>/<action>` block. Returns null
     * (skipping the route) if the entry doesn't satisfy the shape
     * the manifest validator already enforced — defence in depth.
     *
     * The dispatcher distinguishes public-route invocations from IPC
     * invocations by reading `$_SERVER['EIOU_PLUGIN_PUBLIC_ROUTE']`,
     * which nginx sets here. Same __dispatch.php entry script, two
     * envelope-building paths.
     *
     * When `cors_allowed_origins` is present, the block emits CORS
     * response headers, short-circuits OPTIONS preflight to 204, and
     * gates `Access-Control-Allow-Origin` on origin matching. No
     * wildcard support — every origin must appear literally in the
     * manifest list.
     */
    private function renderPublicRouteBlock(
        string $pluginId,
        string $systemUser,
        array $route
    ): ?string {
        $method = (string) ($route['method'] ?? '');
        $action = (string) ($route['action'] ?? '');
        if (!in_array($method, ['GET','POST','PUT','PATCH','DELETE'], true)) {
            return null;
        }
        if (preg_match('/^[a-z][a-z0-9-]{0,63}$/', $action) !== 1) {
            return null;
        }
        $maxBody = (int) ($route['max_body_bytes'] ?? 65536);
        if ($maxBody <= 0 || $maxBody > 1048576) {
            $maxBody = 65536;
        }
        $ratePerMinute = (int) ($route['rate_per_minute'] ?? self::DEFAULT_RATE_PER_MINUTE);
        if ($ratePerMinute <= 0 || $ratePerMinute > 6000) {
            $ratePerMinute = self::DEFAULT_RATE_PER_MINUTE;
        }

        $corsOrigins = $this->validatedCorsOrigins($route['cors_allowed_origins'] ?? null);
        $zone = $this->zoneNameFor($pluginId, $action);

        $bearerRegex = self::PUBLIC_BEARER_REGEX;
        $out = [];
        $out[] = "location = /p/{$pluginId}/{$action} {";

        if ($corsOrigins !== []) {
            // Match the request's Origin against the allow-list. Each
            // match sets $cors_origin to the origin verbatim; an
            // unmatched cross-origin request leaves $cors_origin empty
            // and the browser's same-origin check rejects the response.
            $out[] = "    # CORS allow-list. \$cors_origin stays empty for unmatched";
            $out[] = "    # origins; the browser then refuses to surface the response";
            $out[] = "    # to the calling page.";
            $out[] = "    set \$cors_origin \"\";";
            foreach ($corsOrigins as $origin) {
                $out[] = "    if (\$http_origin = \"{$origin}\") { set \$cors_origin \$http_origin; }";
            }
            // Drop any CORS headers the plugin handler might emit so
            // the host's allow-list is the only Access-Control-* value
            // the client ever sees. A plugin that emitted its own
            // `Access-Control-Allow-Origin: *` couldn't actually widen
            // CORS — browsers reject duplicate ACAO headers — but the
            // resulting CORS-broken response would mask whether the
            // plugin or the host was misconfigured. Hiding the
            // upstream value keeps the host's intent authoritative.
            $out[] = "    fastcgi_hide_header Access-Control-Allow-Origin;";
            $out[] = "    fastcgi_hide_header Access-Control-Allow-Methods;";
            $out[] = "    fastcgi_hide_header Access-Control-Allow-Headers;";
            $out[] = "    fastcgi_hide_header Access-Control-Allow-Credentials;";
            $out[] = "    fastcgi_hide_header Access-Control-Expose-Headers;";
            $out[] = "    fastcgi_hide_header Access-Control-Max-Age;";
            $out[] = "    fastcgi_hide_header Vary;";
            $out[] = "    add_header Access-Control-Allow-Origin  \$cors_origin always;";
            $out[] = "    add_header Access-Control-Allow-Methods \"{$method}, OPTIONS\" always;";
            $out[] = "    add_header Access-Control-Allow-Headers \"Authorization, Content-Type\" always;";
            $out[] = "    add_header Access-Control-Max-Age       600 always;";
            $out[] = "    add_header Vary                          \"Origin\" always;";
            $out[] = "    # Preflight: short-circuit without invoking the plugin pool.";
            $out[] = "    if (\$request_method = OPTIONS) { return 204; }";
        }

        $out[] = "    # Method gate — the manifest pinned exactly one verb per route.";
        $out[] = "    if (\$request_method != {$method}) { return 405; }";
        $out[] = "    # Bearer shape preflight. The plugin does the real auth check;";
        $out[] = "    # this just refuses values that obviously can't be a token.";
        $out[] = "    if (\$http_authorization !~ '{$bearerRegex}') { return 401; }";
        $out[] = "    # Per-bearer rate cap. burst=rate lets one minute of capacity";
        $out[] = "    # absorb a small client retry storm without 503'ing every retry.";
        $out[] = "    limit_req zone={$zone} burst={$ratePerMinute} nodelay;";
        $out[] = "    limit_req_status 429;";
        $out[] = "    client_max_body_size {$maxBody};";
        $out[] = "    fastcgi_pass unix:/run/php/eiou-plugin-{$systemUser}.sock;";
        $out[] = "    include fastcgi_params;";
        $out[] = "    fastcgi_param SCRIPT_FILENAME /etc/eiou/plugins/{$pluginId}/__dispatch.php;";
        $out[] = "    fastcgi_param SCRIPT_NAME     /p/{$pluginId}/{$action};";
        $out[] = "    fastcgi_param EIOU_PLUGIN_PUBLIC_ROUTE 1;";
        $out[] = "    fastcgi_param EIOU_PLUGIN_PUBLIC_ACTION {$action};";
        $out[] = "    fastcgi_read_timeout 30s;";
        $out[] = "}";
        return implode("\n", $out);
    }

    /**
     * Render the http{}-scope nginx file that declares the
     * `limit_req_zone` directives referenced by per-route `limit_req`
     * statements in the snippet. Returned as a separate string because
     * `limit_req_zone` cannot appear inside a server{} or location{}
     * block — the supervisor writes this content to
     * /etc/nginx/conf.d/eiou-plugin-zones.conf (included at http
     * level) alongside the existing /etc/nginx/snippets/eiou-plugins.conf.
     *
     * Zone keying: `$http_authorization` (the full `Bearer <token>`
     * value) so the rate limit is per-bearer-per-route — a single
     * misbehaving customer can't starve well-behaved customers
     * sharing the same plugin. Zone size 1m holds ~16k unique
     * bearers per zone, which is enough for the customer count any
     * single-node plugin is likely to serve in a sliding window.
     *
     * Off when the public-routes feature flag is off; empty string
     * otherwise so the supervisor write doesn't propagate stale zone
     * declarations.
     *
     * @param list<array{
     *     plugin_id:string,
     *     public_routes?:list<array{method:string,action:string,rate_per_minute?:int}>
     * }> $sandboxedPlugins
     */
    public function renderZones(array $sandboxedPlugins): string
    {
        $lines = [
            "# Copyright 2025-2026 Vowels Group, LLC",
            "# Auto-generated by Eiou\\Services\\PluginNginxConfigService.",
            "# Included at http{} scope by /etc/nginx/conf.d/. Hand edits",
            "# are overwritten on every plugin enable/disable.",
            "",
        ];

        if (!$this->publicRoutesEnabled) {
            $lines[] = "# (public plugin routes disabled — EIOU_PUBLIC_PLUGIN_ROUTES off)";
            $lines[] = "";
            return implode("\n", $lines);
        }

        $emitted = 0;
        foreach ($sandboxedPlugins as $entry) {
            $pluginId = (string) ($entry['plugin_id'] ?? '');
            $publicRoutes = $entry['public_routes'] ?? [];
            if (!is_array($publicRoutes)) continue;
            foreach ($publicRoutes as $route) {
                $action = (string) ($route['action'] ?? '');
                $ratePerMinute = (int) ($route['rate_per_minute'] ?? self::DEFAULT_RATE_PER_MINUTE);
                if (preg_match('/^[a-z][a-z0-9-]{0,63}$/', $action) !== 1) continue;
                if (preg_match(PluginUserService::PLUGIN_ID_PATTERN, $pluginId) !== 1) continue;
                if ($ratePerMinute <= 0 || $ratePerMinute > 6000) {
                    $ratePerMinute = self::DEFAULT_RATE_PER_MINUTE;
                }
                $zone = $this->zoneNameFor($pluginId, $action);
                $lines[] = "limit_req_zone \$http_authorization zone={$zone}:1m rate={$ratePerMinute}r/m;";
                $emitted++;
            }
        }

        if ($emitted === 0) {
            $lines[] = "# (no public plugin routes registered)";
        }
        $lines[] = "";
        return implode("\n", $lines);
    }

    /** Default rate cap when a public_routes entry omits rate_per_minute.
     *  60 r/m matches the conservative example in the original feature
     *  spec and is high enough for most synchronous use cases while
     *  still bounding a runaway client.
     */
    public const DEFAULT_RATE_PER_MINUTE = 60;

    /**
     * Derive a stable nginx zone name from a (plugin_id, action) pair.
     * Hashed because plugin ids + actions can together exceed nginx's
     * comfortable zone-name length; sha256[:12] gives 12 hex chars
     * appended to a 3-char prefix for 15 total — well inside any
     * implementation limit.
     */
    public function zoneNameFor(string $pluginId, string $action): string
    {
        $hash = substr(hash('sha256', $pluginId . ':' . $action), 0, 12);
        return 'pp_' . $hash;
    }

    /**
     * Defence-in-depth filter on cors_allowed_origins before it lands
     * verbatim in an nginx config. The manifest validator already
     * pruned bad entries; this drops anything that smells off
     * (non-string, wildcard, embedded quotes, control chars) so even
     * a corrupted code path can't write an `if (...)` clause with
     * escaped quotes.
     *
     * @return list<string>
     */
    private function validatedCorsOrigins(mixed $value): array
    {
        if (!is_array($value)) return [];
        $out = [];
        foreach ($value as $origin) {
            if (!is_string($origin)) continue;
            if (preg_match('#^https?://[a-zA-Z0-9.-]+(:\d{1,5})?$#', $origin) !== 1) continue;
            $out[] = $origin;
        }
        // Cap the list length again at the renderer in case a future
        // caller skips the manifest validator. Keeps the nginx block
        // bounded regardless of who pre-filtered.
        return array_slice($out, 0, 10);
    }

    private function validatePluginId(string $pluginId): void
    {
        if (!preg_match(PluginUserService::PLUGIN_ID_PATTERN, $pluginId)) {
            throw new InvalidArgumentException("Invalid plugin id in snippet: '{$pluginId}'");
        }
    }

    private function validateSystemUser(string $systemUser): void
    {
        $pattern = '/^' . preg_quote(PluginUserService::SYSTEM_USER_PREFIX, '/')
                 . '[a-f0-9]{' . PluginUserService::HASH_HEX_LEN . '}$/';
        if (!preg_match($pattern, $systemUser)) {
            throw new InvalidArgumentException("Invalid system_user in snippet: '{$systemUser}'");
        }
    }
}
