<?php
# Copyright 2025-2026 Vowels Group, LLC

namespace Eiou\Services;

use InvalidArgumentException;

/**
 * PluginNginxConfigService
 *
 * Renders the nginx snippet that routes plugin-served HTTP traffic to
 * each sandboxed plugin's PHP-FPM pool. Lives at
 * /etc/nginx/snippets/eiou-plugins.conf, which is included from
 * eiou-locations.conf so both HTTP and HTTPS server blocks pick it up.
 *
 * URL contract: `/gui/plugin/<plugin-id>/...` routes to that plugin's
 * pool. The plugin id appears in the URL so operators (and tests) can
 * see which plugin a request hit without trawling FPM logs.
 *
 * The snippet is regenerated in full every time any sandboxed plugin
 * enables or disables. PHP renders the content, the supervisor writes
 * it (since /etc/nginx/snippets/ is root-only), and nginx -t verifies
 * it before reload — so a malformed entry from a buggy plugin cannot
 * take down the wallet's routes.
 *
 * Phase 2 of plugin sandboxing — see docs/PLUGIN_SANDBOXING.md.
 */
class PluginNginxConfigService
{
    /**
     * Render the complete nginx snippet from a list of sandboxed
     * plugins. The list MUST be authoritative — anything not in the
     * list ends up with no route after the next reload.
     *
     * @param list<array{plugin_id:string, system_user:string}> $sandboxedPlugins
     */
    public function renderSnippet(array $sandboxedPlugins): string
    {
        $lines = [
            "# Copyright 2025-2026 Vowels Group, LLC",
            "# Auto-generated by Eiou\\Services\\PluginNginxConfigService.",
            "# Hand edits are overwritten on every plugin enable/disable.",
            "# See docs/PLUGIN_SANDBOXING.md.",
            "",
        ];

        if ($sandboxedPlugins === []) {
            $lines[] = "# (no sandboxed plugins enabled)";
            $lines[] = "";
            return implode("\n", $lines);
        }

        foreach ($sandboxedPlugins as $entry) {
            $pluginId = (string) ($entry['plugin_id'] ?? '');
            $systemUser = (string) ($entry['system_user'] ?? '');
            $this->validatePluginId($pluginId);
            $this->validateSystemUser($systemUser);

            // Block shape: every /gui/plugin/<id>/* request lands at the
            // plugin's own FPM socket. The plugin's open_basedir + UID
            // are the real boundary; this just routes traffic to it.
            //
            // SCRIPT_FILENAME pins to the plugin's __dispatch entry
            // point so plugin code never picks the URL — it gets a
            // structured envelope from PHP-FPM with the path captured
            // in PATH_INFO. Plugin must provide /etc/eiou/plugins/<id>/
            // __dispatch.php; absence yields 404 without breaching the
            // pool's open_basedir.
            // fastcgi_split_path_info needs EXACTLY two captures by
            // nginx contract: the first becomes $fastcgi_script_name,
            // the second becomes $fastcgi_path_info. We pin
            // SCRIPT_FILENAME explicitly below so the prefix capture is
            // ornamental, but nginx still requires the second capture
            // to exist or fails `nginx -t` with "must have 2 captures".
            $lines[] = "location ^~ /gui/plugin/{$pluginId}/ {";
            $lines[] = "    fastcgi_pass unix:/run/php/eiou-plugin-{$systemUser}.sock;";
            $lines[] = "    fastcgi_split_path_info ^(/gui/plugin/{$pluginId})(/.*)$;";
            $lines[] = "    include fastcgi_params;";
            $lines[] = "    fastcgi_param SCRIPT_FILENAME /etc/eiou/plugins/{$pluginId}/__dispatch.php;";
            $lines[] = "    fastcgi_param SCRIPT_NAME     /gui/plugin/{$pluginId}/__dispatch.php;";
            $lines[] = "    fastcgi_param PATH_INFO       \$fastcgi_path_info;";
            $lines[] = "    fastcgi_read_timeout 30s;";
            $lines[] = "}";
            $lines[] = "";
        }

        return implode("\n", $lines);
    }

    private function validatePluginId(string $pluginId): void
    {
        if (!preg_match(PluginUserService::PLUGIN_ID_PATTERN, $pluginId)) {
            throw new InvalidArgumentException("Invalid plugin id in snippet: '{$pluginId}'");
        }
    }

    private function validateSystemUser(string $systemUser): void
    {
        $pattern = '/^' . preg_quote(PluginUserService::SYSTEM_USER_PREFIX, '/')
                 . '[a-f0-9]{' . PluginUserService::HASH_HEX_LEN . '}$/';
        if (!preg_match($pattern, $systemUser)) {
            throw new InvalidArgumentException("Invalid system_user in snippet: '{$systemUser}'");
        }
    }
}
