<?php
# Copyright 2025-2026 Vowels Group, LLC

namespace Eiou\Services;

use Eiou\Utils\Logger;
use InvalidArgumentException;

/**
 * PluginPoolService
 *
 * Renders the PHP-FPM pool configuration that runs a sandboxed plugin
 * as its own Unix user (created by PluginUserService) and pins
 * filesystem access to the plugin's directory + a scratch dir. With
 * this in place, a malicious plugin's PHP code cannot:
 *
 *   - Read /etc/eiou/config/.master.key (EACCES at the kernel layer
 *     because the plugin worker runs as eiou-p-<hash>, not www-data)
 *   - Read /etc/eiou/config/userconfig.json (same)
 *   - Open any path outside /etc/eiou/plugins/<id>/ + scratch dir
 *     (open_basedir refuses with "Operation not permitted")
 *   - Shell out via exec/shell_exec/passthru/proc_open/popen/system
 *     (disable_functions)
 *   - Stream-include arbitrary URLs (allow_url_fopen / include = 0)
 *
 * Pool files live in /etc/php/&lt;ver&gt;/fpm/pool.d/eiou-plugin-&lt;hash&gt;.conf and
 * require root to write. PHP-FPM workers run as www-data, so the
 * service hands rendered content + the target path to the supervisor
 * via the routing-apply request file (mirrors PluginUserService). The
 * supervisor in startup.sh writes the file, runs `nginx -t`, then
 * SIGHUP nginx + SIGUSR2 PHP-FPM, and returns a structured result.
 *
 * Phase 2 of plugin sandboxing — see docs/PLUGIN_SANDBOXING.md. Not
 * yet wired into PluginLoader's enable/disable lifecycle; a plugin
 * has to opt in via "sandboxed": true in its manifest (Phase 2 follow-
 * up) for a pool to be generated.
 */
class PluginPoolService
{
    /** Where FPM looks for pool fragments. */
    public const POOL_DIR = '/etc/php/8.3/fpm/pool.d';

    /** Where nginx reads the per-plugin location snippet. */
    public const NGINX_SNIPPET_PATH = '/etc/nginx/snippets/eiou-plugins.conf';

    /** Per-plugin writable scratch dir, included in open_basedir. */
    public const SCRATCH_ROOT = '/var/lib/eiou/plugin-scratch';

    /** Plugin source root (read-only from the plugin's perspective). */
    public const PLUGIN_ROOT = '/etc/eiou/plugins';

    /**
     * disable_functions list. Each entry is a function the plugin's
     * worker must NOT have access to. exec/system family blocks shell-
     * out; assert/eval blocks late-binding code execution. pcntl_exec
     * is the fork-and-execve path; allow_url_fopen / include are set
     * separately via php_admin_value below.
     *
     * Kept deliberately conservative — plugins that need a banned
     * function should make a specific case in code review.
     */
    public const DISABLED_FUNCTIONS = [
        'exec', 'shell_exec', 'passthru', 'proc_open', 'popen', 'system',
        'pcntl_exec', 'assert', 'eval',
    ];

    private ?Logger $logger;

    /** @var callable(string $action, array $payload): array{status:string, error?:string} */
    private $actionExecutor;

    public function __construct(
        ?Logger $logger = null,
        ?callable $actionExecutor = null
    ) {
        $this->logger = $logger;
        $this->actionExecutor = $actionExecutor ?? function (string $action, array $payload): array {
            return $this->executeViaRequestFile($action, $payload);
        };
    }

    /**
     * Render the FPM pool configuration text for one plugin. Public so
     * tests can assert exact content without going through the supervisor.
     */
    public function renderPoolConfig(string $pluginId, string $systemUser): string
    {
        $this->validatePluginId($pluginId);
        $this->validateSystemUser($systemUser);

        $disabled = implode(',', self::DISABLED_FUNCTIONS);
        $basedir = self::PLUGIN_ROOT . '/' . $pluginId . '/:'
                 . self::SCRATCH_ROOT . '/' . $systemUser . '/:'
                 . '/tmp/';

        // pm.max_children kept low — plugins are slow-path observers,
        // not request-serving microservices. If a plugin proves to
        // need more concurrency, it can override via a manifest field
        // in a follow-up. request_terminate_timeout caps a runaway
        // plugin's request to 30s so it cannot wedge a worker forever.
        return <<<EOT
[eiou-plugin-{$pluginId}]
; Auto-generated by Eiou\\Services\\PluginPoolService. Do not edit by
; hand — PluginPoolService::ensurePool() overwrites this file on every
; plugin enable. Manual changes are lost on the next reload.

user = {$systemUser}
group = {$systemUser}
listen = /run/php/eiou-plugin-{$systemUser}.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0660

pm = ondemand
pm.max_children = 4
pm.process_idle_timeout = 10s

request_terminate_timeout = 30s
request_slowlog_timeout = 5s
slowlog = /var/log/php-fpm-{$systemUser}-slow.log

php_admin_value[open_basedir]      = {$basedir}
php_admin_value[disable_functions] = {$disabled}
php_admin_value[allow_url_fopen]   = 0
php_admin_value[allow_url_include] = 0

EOT;
    }

    /**
     * Path the pool config lives at on disk. Stable function of the
     * plugin id so the supervisor and reconcile() can find each other.
     */
    public function poolPath(string $pluginId): string
    {
        $this->validatePluginId($pluginId);
        return self::POOL_DIR . '/eiou-plugin-' . $pluginId . '.conf';
    }

    /**
     * Apply a pool + nginx snippet for a sandboxed plugin.
     *
     * The caller passes:
     *   - $pluginId    — the plugin id whose pool is being applied
     *   - $systemUser  — the eiou-p-<hash> user (from PluginUserService)
     *   - $nginxSnippet — the FULL nginx routing snippet (covering EVERY
     *                     sandboxed plugin, not just this one) so the
     *                     supervisor can write it atomically without
     *                     needing to know who else is enabled.
     *
     * Returns true if the supervisor accepted the request and reloads
     * succeeded; false otherwise (including nginx -t failure). On false,
     * NO files were changed — the supervisor refuses to reload when its
     * config-test step fails.
     */
    public function applyPool(
        string $pluginId,
        string $systemUser,
        string $nginxSnippet
    ): bool {
        $this->validatePluginId($pluginId);
        $this->validateSystemUser($systemUser);

        $poolConfig = $this->renderPoolConfig($pluginId, $systemUser);

        $result = ($this->actionExecutor)('apply-pool', [
            'plugin_id'     => $pluginId,
            'system_user'   => $systemUser,
            'pool_path'     => $this->poolPath($pluginId),
            'pool_config'   => $poolConfig,
            'nginx_snippet' => $nginxSnippet,
        ]);

        $ok = ($result['status'] ?? '') === 'ok';
        $this->log($ok ? 'info' : 'warning', 'plugin_pool_apply', [
            'plugin' => $pluginId,
            'system_user' => $systemUser,
            'result' => $result,
        ]);
        return $ok;
    }

    /**
     * Remove a plugin's pool and refresh the nginx snippet (which now
     * omits this plugin). Supervisor handles the file deletion + reload
     * the same way applyPool does.
     */
    public function dropPool(string $pluginId, string $nginxSnippet): bool
    {
        $this->validatePluginId($pluginId);

        $result = ($this->actionExecutor)('drop-pool', [
            'plugin_id'     => $pluginId,
            'pool_path'     => $this->poolPath($pluginId),
            'nginx_snippet' => $nginxSnippet,
        ]);

        $ok = ($result['status'] ?? '') === 'ok';
        $this->log($ok ? 'info' : 'warning', 'plugin_pool_drop', [
            'plugin' => $pluginId,
            'result' => $result,
        ]);
        return $ok;
    }

    private function validatePluginId(string $pluginId): void
    {
        if (!preg_match(PluginUserService::PLUGIN_ID_PATTERN, $pluginId)) {
            throw new InvalidArgumentException("Invalid plugin id: '{$pluginId}'");
        }
    }

    private function validateSystemUser(string $systemUser): void
    {
        $pattern = '/^' . preg_quote(PluginUserService::SYSTEM_USER_PREFIX, '/')
                 . '[a-f0-9]{' . PluginUserService::HASH_HEX_LEN . '}$/';
        if (!preg_match($pattern, $systemUser)) {
            throw new InvalidArgumentException("Invalid system_user: '{$systemUser}'");
        }
    }

    /**
     * Default request-file executor. Synchronous RPC against the
     * supervisor's plugin_routing_poller in startup.sh.
     *
     * @return array{status:string, error?:string}
     */
    private function executeViaRequestFile(string $action, array $payload): array
    {
        if (!in_array($action, ['apply-pool', 'drop-pool'], true)) {
            return ['status' => 'failed', 'error' => "unknown action: {$action}"];
        }

        $reqId = bin2hex(random_bytes(8));
        $reqPath = "/tmp/eiou-routing-req-{$reqId}.json";
        $resPath = "/tmp/eiou-routing-res-{$reqId}.json";

        $body = json_encode(array_merge($payload, [
            'ts' => time(),
            'action' => $action,
        ]));
        if ($body === false) {
            return ['status' => 'failed', 'error' => 'encode failed'];
        }

        if (@file_put_contents($reqPath, $body) === false) {
            return ['status' => 'failed', 'error' => "could not write request"];
        }
        @chmod($reqPath, 0644);

        // Generous timeout — `nginx -t` plus two reloads can take a
        // few seconds under load. The supervisor's own internal
        // timeout protects against hangs.
        $deadline = time() + 15;
        while (time() < $deadline) {
            if (is_file($resPath)) {
                $raw = @file_get_contents($resPath);
                @unlink($resPath);
                @unlink($reqPath);
                if ($raw === false) {
                    return ['status' => 'failed', 'error' => 'unreadable result'];
                }
                $decoded = json_decode($raw, true);
                if (!is_array($decoded)) {
                    return ['status' => 'failed', 'error' => 'malformed result'];
                }
                return [
                    'status' => (string) ($decoded['status'] ?? 'failed'),
                    'error'  => isset($decoded['error']) ? (string) $decoded['error'] : '',
                ];
            }
            usleep(200000); // 200 ms
        }

        @unlink($reqPath);
        return ['status' => 'failed', 'error' => 'timed out waiting for supervisor'];
    }

    private function log(string $level, string $message, array $context): void
    {
        if ($this->logger === null) return;
        $this->logger->{$level}($message, $context);
    }
}
